---
- name: Set UName Property
  shell: uname -r
  ignore_errors: yes
  register: uname_result
- debug: msg="{{ uname_result.stdout }}"

- name: Set Current User
  become: no
  shell: whoami
  register: user
- debug: msg="{{ user.stdout }}"


# ATTENTION: this task can potentially create new users!
- name: Add users to the docker group
  user:
    name: "{{ user.stdout }}"
    groups: docker
    append: yes

# Install Container Top Utility
- name: Install Container Top
  get_url:
    url: https://github.com/bcicen/ctop/releases/download/v0.6.1/ctop-0.6.1-linux-amd64
    dest: /usr/local/bin/ctop
    mode: 766
