version: '2'
services:
  device-js:
    build: js
    image: localhost:5000/iot-device-js:latest
    environment:
      DEVICE: $DEVICE_JS
      DEVICE_CONNECTION_STRING: $DEVICE_JS_CONNECTION
      MESSAGE_INTERVAL: 2
      LOG_LEVEL: info
  device-net:
    build: dotnet
    image: localhost:5000/iot-device-net:latest
    environment:
      DEVICE: $DEVICE_NET
      DEVICE_CONNECTION_STRING: $DEVICE_NET_CONNECTION
      MESSAGE_INTERVAL: 2000
      LOG_LEVEL: info
